### ISSUE TITLE
Issue in Exercise 2

### ISSUE THREAD

**Issue by Shivashant25** [microsoft/MCW-Cloud-native-applications#303] opened 2022-02-15 17:13 UTC
In Exercise - 2> Task - 2> step - 22, The api deployment is not getting into state and it's stuck at `waiting`  state with **ERROR: CrashLoopBackOff**. please look into this issue as soon as possible as we have labs scheduled.

![image](https://user-images.githubusercontent.com/81952290/154113076-20eccebb-f32f-467f-ac5a-a445d7de2154.png)

![image](https://user-images.githubusercontent.com/81952290/154113138-604f3abb-a489-47ad-b315-7c0fc1c70015.png)

**Comment by hatboyzero** [comment] 2022-02-17 16:36
Can you provide more detail from the `api` container?  Possibly some logs from the container so that we can determine the root cause of the `CrashLoopBackOff` state?

**Comment by Shivashant25** [comment] 2022-02-17 17:01
Hi @hatboyzero

We tried troubleshooting from our end and we found that node version: `node:alpine AS base` in `https://github.com/microsoft/MCW-Cloud-native-applications/blob/main/Hands-on%20lab/lab-files/developer/content-api/Dockerfile` is not supporting. Were you able to reproduce this issue?

**Comment by EstebanZ** [comment] 2022-02-21 20:09
Hi guys, I have same problem, as @Shivashant25  mentioned the version node alpine is latest (current: v17.5.0, is not LTS).

I attacht api pod logs:

> 21/2/2022, 16:51:34 > content-api@0.0.0 start
21/2/2022, 16:51:34 > node ./server.js
21/2/2022, 16:51:34 21/2/2022, 16:51:35 /usr/src/app/node_modules/mongoose/lib/cursor/QueryCursor.js:150
21/2/2022, 16:51:35 QueryCursor.prototype.map = function(fn) {
21/2/2022, 16:51:35 ^
21/2/2022, 16:51:35 21/2/2022, 16:51:35 TypeError: Cannot assign to read only property 'map' of object '#<QueryCursor>'
21/2/2022, 16:51:35    at Object.<anonymous> (/usr/src/app/node_modules/mongoose/lib/cursor/QueryCursor.js:150:27)
21/2/2022, 16:51:35    at Module._compile (node:internal/modules/cjs/loader:1097:14)
21/2/2022, 16:51:35    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1151:10)
21/2/2022, 16:51:35    at Module.load (node:internal/modules/cjs/loader:975:32)
21/2/2022, 16:51:35    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
21/2/2022, 16:51:35    at Module.require (node:internal/modules/cjs/loader:999:19)
21/2/2022, 16:51:35    at require (node:internal/modules/cjs/helpers:102:18)
21/2/2022, 16:51:35    at Object.<anonymous> (/usr/src/app/node_modules/mongoose/lib/query.js:12:21)
21/2/2022, 16:51:35    at Module._compile (node:internal/modules/cjs/loader:1097:14)
21/2/2022, 16:51:35    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1151:10)
21/2/2022, 16:51:35    at Module.load (node:internal/modules/cjs/loader:975:32)
21/2/2022, 16:51:35    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
21/2/2022, 16:51:35    at Module.require (node:internal/modules/cjs/loader:999:19)
21/2/2022, 16:51:35    at require (node:internal/modules/cjs/helpers:102:18)
21/2/2022, 16:51:35    at Object.<anonymous> (/usr/src/app/node_modules/mongoose/lib/index.js:27:15)
21/2/2022, 16:51:35    at Module._compile (node:internal/modules/cjs/loader:1097:14)
21/2/2022, 16:51:35 21/2/2022, 16:51:35 Node.js v17.5.0
21/2/2022, 16:51:35 npm notice
21/2/2022, 16:51:35 npm notice New minor version of npm available! 8.4.1 -> 8.5.1
21/2/2022, 16:51:35 npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.5.1>
21/2/2022, 16:51:35 npm notice Run `npm install -g npm@8.5.1` to update!
21/2/2022, 16:51:35 npm notice
31/12/1969, 21:00:00 ===========PLEASE NOTE THAT THERE MAY BE MISSING DATA HERE.===========

I found the following [issue in mongoose repo](https://github.com/Automattic/mongoose/issues/11377).
This issue could be fix using however  

This issue would be solved using node:16.5.0-alpine instead of node:alpine (latest version).

**Comment by hatboyzero** [comment] 2022-02-24 02:27
Should be resolved by #308

**Closed** 2022-02-24 16:17 UTC
