### ISSUE TITLE
issue: Exercise 1 Step 15: can not show detailed documents on Data Explore

### ISSUE THREAD

**Issue by teo-ma** [microsoft/MCW-Cloud-native-applications#325] opened 2022-05-10 03:06 UTC
Hello,

I found Exercise 1 Step 15: can not show detailed documents on Data Explore on HOL step-by-step - Cloud-native applications.md. It threw the below exceptions.It worked fine on previous lab steps. Any suggestion?

Error reading document: , Payload: {"db":"contentdb","coll":"sessions","resourceUrl":"https://fabmedical-ma7.mongo.cosmos.azure.com:443/dbs/contentdb/colls/sessions/54b321f979cfa6002dd73477%5B%5BString%5D%5D54b321f979cfa6002dd73477%5B%5BString","rid":"54b321f979cfa6002dd73477%5B%5BString%5D%5D54b321f979cfa6002dd73477%5B%5BString","rtype":"docs","sid":"e0c6ee30-5425-4a43-b5c7-5cedadc57797","rg":"fabmedical-ma7","dba":"fabmedical-ma7","pk":"id"}

<img width="1934" alt="image" src="https://user-images.githubusercontent.com/16115524/167534379-959f5a6b-0ee1-4501-8fec-39dfe28ed132.png">

Thanks,
Teo

**Comment by hatboyzero** [comment] 2022-05-16 18:16
@teo-ma Could you verify that this is still happening?  I cannot reproduce this in my environment.

**Comment by timahenning** [comment] 2022-05-23 15:29
Hi @teo-ma,

Can you confirm the problem is still occurring?  If the problem is still occurring, what region are your resources located in?  We will be closing the issue in a couple of days.

**Comment by DawnmarieDesJardins** [comment] 2022-05-25 19:11
@teo-ma 
Hi Teo.  I'm going to close this issue since we cannot reproduce it.  When you get a chance to go through the lab again, if you get the same error, please let us know with updated screenshots and we'll reopen and review.  Thanks!

**Closed by DawnmarieDesJardins** 2022-05-25 19:11 UTC
