### ISSUE TITLE
Issue in Hands on lab (Before the HOL): Task 4, step 3

### ISSUE THREAD

**Issue by EstebanZ** [microsoft/MCW-Cloud-native-applications#304] opened 2022-02-16 20:21 UTC
Before the end step 3, using bash on Azure Cloud Shell, the script [create_azure_resources.sh ](https://github.com/microsoft/MCW-Cloud-native-applications/blob/main/Hands-on%20lab/lab-files/developer/scripts/create_azure_resources.sh) request username and password github but after that enter credentials the terminal show this message:

![image](https://user-images.githubusercontent.com/9389266/154347583-7fafddde-df37-4fa3-98c5-6f564e67a1a0.png)

Workaround:

After that push repo manually using token generated by [Follow this link](https://github.com/settings/tokens/new?scopes=repo&description=GitHub%20Secrets%20CLI) (Task 4: Set up Azure Cloud Shell environment, Step 1)
But before token generate you add manually the follow scops
- workflow
- read:org

`cd ~/Fabmedical`
`git push https://<GITHUB_ACCESS_TOKEN>@github.com/<GITHUB_USERNAME>/Fabmedical.git`

**Comment by hatboyzero** [comment] 2022-02-17 16:48
The Github CLI (gh) should be setting up the credential store for git operations, per lines 90-92 of create_azure_resources.sh

```sh
GITHUB_TOKEN=$MCW_GITHUB_TOKEN
cd ~/Fabmedical
echo $GITHUB_TOKEN | gh auth login --with-token
```

An issue with the Git credential store not being configured correctly has been reported [here](https://github.com/cli/cli/issues/4351).  As such, could you verify the following output when executing `git config -l | grep credential` is along the lines of:

```sh
credential.helper=store
```

If it is not, please attempt to manually set the credential store via the following and verify if this corrects the behavior:

```sh
git config --global credential.helper store
```

If that corrects the behavior on your end, we can update the script with that explicit command to set up the Git credential store prior to authorizing with the `gh` CLI tool.

**Comment by EstebanZ** [comment] 2022-02-17 20:17
Hi @hatboyzero , #305  does not allow me to verify what you instructions today 😞

**Comment by EstebanZ** [comment] 2022-02-21 17:48
I changed k8s version (1.21.9) on [azuredeploy.json](https://github.com/microsoft/MCW-Cloud-native-applications/blob/main/Hands-on%20lab/lab-files/developer/scripts/azuredeploy.json) file locally to tries you suggestion.

When i run 'git config -l | grep credential' the output is empty; so i run 'git config --global credential.helper store' after that the output is:

`credential.helper=store`

But CLI (gh) still request credentials, 

![image](https://user-images.githubusercontent.com/9389266/155004947-fab3a421-3ac8-4e3a-abb1-b40301b886f5.png)

**Comment by hatboyzero** [comment] 2022-02-24 02:20
Can you provide the value, if any, of the MCW_GITHUB_URL environment variable of the environment in which you are executing this?

**Comment by hatboyzero** [comment] 2022-02-24 02:32
Should be resolved in #308

**Comment by DawnmarieDesJardins** [comment] 2022-02-24 16:19
Closing issue with merge of PR #308

**Comment by EstebanZ** [comment] 2022-03-02 19:44
hi, the PR #308 does not solve this issue. The create_azure_resources.sh script still requires Github credentials.

![image](https://user-images.githubusercontent.com/9389266/156437167-6a0b06d5-8a6d-4062-8ec3-3422c3401565.png)

As a workaround:
- when the script finishes (I enter correct or incorrect credentials, it makes no difference):

cd ~/Fabmedical
git push https://<GITHUB_ACCESS_TOKEN>@github.com/<GITHUB_USERNAME>/Fabmedical.git

**Comment by DawnmarieDesJardins** [comment] 2022-03-11 22:39
Reopening this issue so I can track further investigation. 
@hatboyzero - any additional advice?

**Comment by hatboyzero** [comment] 2022-03-16 12:20
On line 27 of the create_azure_resources.sh script, I changed to correct the URL used to access and update the repository in pull request #308. Unless the end-user sets the MCW_GITHUB_URL environment variable before running the script, it should (and does, through my testing) construct the correct URL. TL;DR I cannot reproduce the behavior. As far as I can tell in my environment, it is working correctly.

**Comment by timahenning** [comment] 2022-03-21 20:36
Hi @EstebanZ ,

We cannot reproduce the issue on our side if we use #308. Please try this solution and let us know if does not work.

**Closed by timahenning** 2022-03-21 20:36 UTC
