### ISSUE TITLE
npm install applicationinsights --save takes more time

### ISSUE THREAD

**Issue by anushabc** [microsoft/MCW-Cloud-native-applications#231] opened 2021-02-02 21:23 UTC
Exercise 5 task 4 step 3, it's more than 60mins since I have run the command but it's still running with the warning message

![image](https://user-images.githubusercontent.com/66515706/106664201-bd614600-65ca-11eb-8ebc-d25ac19b3ec6.png)

**Comment by saimachi** [comment] 2021-02-05 05:37
Hi @anushabc,

I am not encountering the same issue in my environment. From the recommendations I've read, try deleting the `package-lock.json` file. Then, try deleting the `node_modules` folder (`rm -rf node_modules/`). Then, try executing `npm install`. At this point, you should be able to install the Application Insights SDK without a problem.

**Comment by DawnmarieDesJardins** [comment] 2021-02-10 18:27
@anushabc 
Hello!  Did Sai's comment solve the issue for you?

**Comment by anushabc** [comment] 2021-02-15 06:08
Hi @DawnmarieDesJardins  we will test the lab once the 404 issue is fixed and provide you an update

**Comment by sumitmalik51** [comment] 2021-02-19 18:08
hello @saimachi,, we have tested the lab today and this step took approx. 30 minutes to complete the npm installation.

**Comment by saimachi** [comment] 2021-02-19 21:32
Hi @sumitmalik51 and @anushabc,

I'll be taking a look at the lab with a fresh environment. I'll let you know if I encounter this error.

Could you provide me some information about the particular step that caused the package installation to take so long? A log from the package installation would be preferable.

**Comment by sumitmalik51** [comment] 2021-02-19 21:37
Hello @saimachi, 

The step is Exercise 5 task 4 step 3, Also I have shared one active environment URL to @DawnmarieDesJardins to troubleshoot this issue. Could you please let us know your email address so that I will add you in that thread, or you can reach out to me at sumit.kumar@spektrasystems.com.
Thanks

**Comment by crpietschmann** [comment] 2021-02-21 17:06
@sumitmalik51 In the environment, I see the 'web' app is broken due to an error with the applicationinsights package not being found. Did you get it to install correctly? I thought the "bug" was that it just took a long time?

**Comment by sumitmalik51** [comment] 2021-02-21 17:12
Hi @crpietschmann, yes we installed the applicationinsights correctly that took around 30 minutes to complete. did you reinstall the application insights? Also if you have reinstalled applicationinsights, does that web app 404 #214  issue fixed?

**Comment by crpietschmann** [comment] 2021-03-05 19:54
if the NPM package takes "too long" to install, there's nothing I can do about that as it's an NPM issue in that case. Every time I've installed the Application Insights NPM package, it's only taken a minute to complete. This is not an issue we can do anything about.

**Comment by DawnmarieDesJardins** [comment] 2021-03-05 21:07
Closing issue.  Not able to reproduce delay in author's environment.

**Closed by DawnmarieDesJardins** 2021-03-05 21:07 UTC

**Comment by snpdev** [comment] 2021-04-16 17:26
I have experienced the same problem on two different occasions with the lab VM provisioned by Spektra Systems. My work around is to perform [Exercise 5 | Task 3 | Steps 1-6](https://github.com/microsoft/MCW-Cloud-native-applications/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Cloud-native%20applications%20-%20Developer%20edition.md#task-3-perform-a-rolling-update) in a local Bash terminal (in VS Code, for example).

**Comment by nmeisenzahl** [comment] 2021-04-28 14:29
We are facing the same issues. Looks like it might be related to insufficient disk space in the Cloud Shell.
![image](https://user-images.githubusercontent.com/28020936/116420993-c2870780-a83e-11eb-88ae-2873f5c41476.png)
